### ISSUE TITLE
cannot read property '0' of undefined

### ISSUE THREAD

**Issue by damovsky** [puemos/aws-lambda-ecr-cleaner#1]
Hi,
many thanks for your project. I use it for last couple of weeks. This is more request for help than bug report....

Since 4th of Jan 2017 your aws-lambda-ecr-cleaner starts failing on error
```{"errorMessage":"Cannot read property '0' of undefined","errorType":"TypeError","stackTrace":["/var/task/lib/index.js:152:37","Array.map (native)","/var/task/lib/index.js:149:18","tryCatcher (/var/task/node_modules/bluebird/js/release/util.js:16:23)","Promise._settlePromiseFromHandler (/var/task/node_modules/bluebird/js/release/promise.js:510:31)","Promise._settlePromise (/var/task/node_modules/bluebird/js/release/promise.js:567:18)","Promise._settlePromise0 (/var/task/node_modules/bluebird/js/release/promise.js:612:10)","Promise._settlePromises (/var/task/node_modules/bluebird/js/release/promise.js:691:18)","Promise._fulfill (/var/task/node_modules/bluebird/js/release/promise.js:636:18)","Response.<anonymous> (/var/task/node_modules/bluebird/js/release/nodeback.js:42:21)","Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:355:18)","Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)","Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)","Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:668:14)","Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)"]}```

Do you have any idea what could be wrong?  I'm not aware of any changes made in code nor in AWS...Do you also use this project? can you try to run it today to see if it works for you or not?

Thanks
Martin

**Comment by puemos** [comment]
I checked yesterday and everything was working well.
**BUT** I changed to way of getting the image pushed time so it will be aligned with the aws ecr API

check **v0.3.0**

thank you for your issue !!

**Comment by damovsky** [comment]
Hi,
sorry for late response. I forgot to say thanks for this PR! it works ;-)

Martin
